version: "3.9"

services:
  app-v1:
    build: ./app-v1
    container_name: app-v1
    ports:
      - "5001:5000"
    networks:
      - ab_net

  app-v2:
    build: ./app-v2
    container_name: app-v2
    ports:
      - "5002:5000"
    networks:
      - ab_net

  nginx-lb:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ab_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ab_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - ab_net
    depends_on:
      - prometheus

networks:
  ab_net:
    driver: bridge
